# Generated by Django 2.2.1 on 2020-02-13 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definizione', models.CharField(max_length=240)),
                ('rango', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'cariche',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'verbose_name_plural': 'Gradi',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=240)),
                ('cognome', models.CharField(blank=True, max_length=240)),
                ('nascitacity', models.CharField(blank=True, max_length=240)),
                ('nascitadata', models.DateTimeField()),
                ('decedutodata', models.DateTimeField()),
                ('residenza', models.CharField(blank=True, max_length=30)),
                ('tessera', models.CharField(blank=True, max_length=30)),
                ('congedodata', models.DateTimeField()),
                ('congedoreparto', models.DateTimeField()),
                ('socioemail', models.EmailField(max_length=254)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SociRegistrati', to=settings.AUTH_USER_MODEL)),
                ('gradoinservizio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soci.Grado')),
            ],
            options={
                'verbose_name_plural': 'soci',
            },
        ),
        migrations.CreateModel(
            name='CaricaStorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incaricadal', models.DateTimeField()),
                ('incaricaal', models.DateTimeField()),
                ('Carica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Storico', to='soci.Carica')),
                ('Socio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cariche', to='soci.Socio')),
            ],
        ),
    ]
