# Generated by Django 2.2.1 on 2020-02-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soci', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caricastorico',
            options={'verbose_name_plural': 'storicocariche'},
        ),
    ]
