# Generated by Django 2.2.1 on 2020-02-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soci', '0002_auto_20200213_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='decedutodata',
            field=models.DateTimeField(null=True),
        ),
    ]
