# Generated by Django 2.2.1 on 2020-02-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soci', '0003_auto_20200213_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='decedutodata',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
