# Generated by Django 2.2.1 on 2020-01-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('datainizio', models.DateTimeField(blank=True)),
                ('luogo', models.CharField(max_length=240)),
            ],
            options={
                'verbose_name': 'Evidenza',
                'verbose_name_plural': 'Evidenze',
            },
        ),
    ]
