# Generated by Django 2.2.1 on 2019-12-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoPlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=240)),
                ('picture', models.FileField(upload_to='images/')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhotoPlusEvento', to='events.Evento')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
