# Generated by Django 2.2.1 on 2019-12-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_photoplus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoplus',
            options={'verbose_name': 'PhotoPlus', 'verbose_name_plural': 'PhotosPlus'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='anno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
